djangoTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('polls/', include('polls.urls')),
    path('fanxiangce/', include('fanxiangce.urls')),
]

handler404 = 'fanxiangce.views.error.page_not_found2'
handler500 = 'fanxiangce.views.error.page_error'

fanxiangce/urls.py
from django.urls import path, re_path

from . import views

app_name = 'fanxiangce'

urlpatterns = [
    # re_path(r'^aaa/(?P<num>\d)?$', views.page, name='page'),
    # path('about/', TemplateView.as_view(template_name="about.html")),
    path('', views.index, name='index'),
    path('photo/<int:photo_id>', views.photo, name='photo'),
    path('user/<str:username>', views.albums, name='albums'),
    path('album/<int:album_id>', views.album, name='album'),
    path('explore', views.explore, name='explore'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('confirm/<token>', views.confirm, name='confirm'),
    path('unconfirmed', views.unconfirmed, name='unconfirmed'),
    path('resend_confirmation', views.resend_confirmation, name='resend_confirmation'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

fanxiangce/models/album.py
# coding: utf-8

from django.db import models
from datetime import datetime


class Album(models.Model):
    title = models.CharField('标题', max_length=64, null=True, blank=True)
    about = models.TextField(null=1, blank=1)
    cover = models.CharField(max_length=64, null=1, blank=1)
    type = models.IntegerField(default=0)
    tag = models.CharField(max_length=64, null=1, blank=1)
    no_public = models.BooleanField(default=True)
    no_comment = models.BooleanField(default=1)
    asc_order = models.BooleanField(default=1)
    timestamp = models.DateTimeField(default=datetime.now)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='albums', null=True, blank=True)
    album_liked = models.ManyToManyField('auth.User', related_name='album_likes', blank=1)

    def __str__(self):
        return self.title

fanxiangce/models/comment.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Comment(models.Model):
    body = models.TextField(null=1, blank=1)
    timestamp = models.DateTimeField(default=datetime.now)
    disabled = models.BooleanField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=1, blank=1)
    photo = models.ForeignKey('Photo', on_delete=models.CASCADE, related_name='comments', null=1, blank=1)

fanxiangce/models/message.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Message(models.Model):
    body = models.TextField(null=1, blank=1)
    timestamp = models.DateTimeField(default=datetime.now)
    disabled = models.BooleanField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages', null=1, blank=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_messages', null=1, blank=1)

fanxiangce/models/photo.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from .album import Album
from datetime import datetime


class Photo(models.Model):
    url = models.CharField(max_length=200, null=True, blank=True)
    url_s = models.CharField(max_length=200, null=True, blank=True)
    url_t = models.CharField(max_length=200, null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(default=datetime.now, null=True, blank=True)
    order = models.IntegerField(null=True, blank=True, default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者', related_name='photos', null=1, blank=True)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, verbose_name='相册', related_name='photos', null=1, blank=True)
    photo_liked = models.ManyToManyField(User, verbose_name='收藏者', related_name='photo_likes', blank=True)

fanxiangce/models/user.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from .photo import Photo
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer  # 生成令牌用
from django.conf import settings
from django.utils import timezone
from django.shortcuts import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=1)

    status = models.CharField(max_length=64, null=1, blank=1)
    liked = models.IntegerField(default=0)
    confirmed = models.BooleanField(default=False)
    like_public = models.BooleanField(default=1)
    name = models.CharField(max_length=64, null=1, blank=1)
    location = models.CharField(max_length=64, null=1, blank=1)
    website = models.CharField(max_length=64, null=1, blank=1)
    background = models.CharField(max_length=64, null=1, blank=1)
    about_me = models.TextField(null=1, blank=1)
    member_since = models.DateTimeField(default=timezone.now)
    last_seen = models.DateTimeField(default=timezone.now)
    avatar_hash = models.CharField(max_length=32, null=1, blank=1)
    followed = models.ManyToManyField(User, blank=True, related_name='followers')

    @property
    def followed_photos(self):
        photo_ids = []
        for f in self.followed.all():
            for photo in f.photos:
                if photo.id not in photo_ids:
                    photo_ids.append(photo.id)
        return Photo.objects.filter(id__in=photo_ids)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(settings.SECRET_KEY, expiration)
        return s.dumps({'confirm': self.user.id})


class MyUser(User):
    class Meta:
        proxy = True


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

fanxiangce/forms.py
# coding: utf-8

from django import forms


class CommentForm(forms.Form):
    body = forms.CharField(label='留言')


class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=64, widget=forms.TextInput(attrs={'class': 'form-control form-input'}))
    password = forms.CharField(label='密 码', widget=forms.PasswordInput(attrs={'class': 'form-control form-input'}))


class RegisterForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=64, widget=forms.TextInput(attrs={'class': 'form-control form-input'}))
    email = forms.EmailField(label='邮箱', max_length=64, widget=forms.TextInput(attrs={'class': 'form-control form-input'}))
    name = forms.CharField(label='昵称', max_length=64, widget=forms.TextInput(attrs={'class': 'form-control form-input'}))
    password = forms.CharField(label='密码', widget=forms.PasswordInput(attrs={'class': 'form-control form-input'}))
    password2 = forms.CharField(label='确认密码', widget=forms.PasswordInput(attrs={'class': 'form-control form-input'}))

fanxiangce/views.py
# coding: utf-8
from .models import Album, Message, Photo, Comment
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, reverse, render_to_response
from django.core.paginator import Paginator
from django.conf import settings
from .forms import LoginForm, CommentForm, RegisterForm
from django.contrib import messages, auth
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer  # 生成令牌用
from django.contrib.auth.hashers import make_password   # 注册用户时候保存密码加密问题
from django.template import loader
from django.core.mail import EmailMultiAlternatives


def page_not_found2(request, exception):
    return render_to_response('fanxiangce/404.html')


def page_error(request):
    return render_to_response('fanxiangce/500.html')


def album(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    placeholder = 'http://p1.bpimg.com/567591/15110c0119201359.png'
    photo_amount = len(album.photos)
    if photo_amount == 0:
        album.cover = placeholder
    elif photo_amount != 0 and album.cover == placeholder:
        album.cover = album.photos[0].path
    if request.user != album.author and album.no_public:
        raise Http404('相册未公开')
    page = request.GET.get('page', 1)
    if album.asc_order:
        order_by = 'id'
    else:
        order_by = '-id'
    pagination = Paginator(album.photos.all().order_by(order_by), per_page=settings.FANXIANGCE_PHOTOS_PER_PAGE)
    photos = pagination.get_page(page)
    if len(photos) == 0:
        no_pic = True
    else:
        no_pic = False

    if request.user.is_authenticated:
        likes = request.user.photo_likes.all().order_by('id')
        likes = [{'id': like.like_photo, 'timestamp': like.timestamp, 'url_t': like.like_photo.url_t} for like in likes]
    else:
        likes = ""

    return render(request, 'fanxiangce/album.html', {
        'album': album,
        'photos': photos,
        'likes': likes,
        'no_pic': no_pic,
    })


def albums(request, username):
    user = get_object_or_404(User, username=username)
    page = request.GET.get('page', 1)

    album_paginator = Paginator(user.albums.all().order_by('-id'), settings.FANXIANGCE_ALBUMS_PER_PAGE)
    albums = album_paginator.get_page(page)
    photo_count = sum([len(album.photos.all()) for album in albums])
    album_count = len(albums)

    about_me = user.profile.about_me

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                body = form.cleaned_data['body']
                message = Message(body=body, author=request.user.id, user=user)
                message.save()
                messages.success(request, '你的评论已经发表')
                return HttpResponseRedirect(reverse('fanxiangce:albums', args=(username,)))
            else:
                messages.error(request, '请先登陆')
    else:
        form = CommentForm()

    comments = user.messages.all().order_by('id')

    return render(request, 'fanxiangce/albums.html', {
        'form': form,
        'comments': comments,
        'user': user,
        'albums': albums,
        'album_count': album_count,
        'photo_count': photo_count,
        'about_me': about_me,
    })


def unconfirmed(request):
    return render(request, 'fanxiangce/unconfirmed.html')


@login_required
def resend_confirmation(request):
    token = request.user.profile.generate_confirmation_token()
    text_content = ''
    confirm_url = request.build_absolute_uri(reverse('fanxiangce:confirm', args=[token]))
    html_content = loader.render_to_string('fanxiangce/confirm.html',
                                           {'user': request.user, 'token': token, 'confirm_url': confirm_url})
    msg = EmailMultiAlternatives('账户邮件确认', text_content, settings.DEFAULT_FROM_EMAIL, [request.user.email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
    messages.info(request, '确认邮件已发送到你的邮箱，请查收')
    return HttpResponseRedirect(reverse('fanxiangce:index'))


@login_required()
def confirm(request, token):
    def do_confirm():
        s = Serializer(settings.SECRET_KEY)
        try:
            data = s.loads(token)
        except Exception:
            return False

        if data.get('confirm') != request.user.id:
            return False

        request.user.profile.confirmed = True
        request.user.profile.save()
        return True

    if do_confirm():
        messages.success(request, '你的账户已经确认')
    else:
        messages.warning(request, '抱歉，验证链接无效或已经过期')

    return HttpResponseRedirect(reverse('fanxiangce:index'))


def explore(request):
    photos = Photo.objects.all().order_by('-id')
    photos = [photo for photo in photos if not photo.album.no_public and photo.author != request.user]
    photo_type = "new"
    return render(request, 'fanxiangce/explore.html', {
        'photos': photos,
        'photo_type': photo_type,
    })


def index(request):
    if request.user.is_authenticated and request.user.username != 'admin':
        photos = request.user.profile.followed_photos
    else:
        photos = Photo.objects.all()[:20]
    context = {
        'photos': photos
    }
    return render(request, 'fanxiangce/index.html', context)


def login(request):
    res = True
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = auth.authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                auth.login(request, user)
                messages.success(request, '登陆成功')
                return HttpResponseRedirect(reverse('fanxiangce:index'))
            else:
                res = False
                messages.error(request, '用户名或者密码错误')
        else:
            res = False
            messages.error(request, '输入错误')
    if res:
        return render(request, 'fanxiangce/login.html', {'form': form})
    else:
        return HttpResponseRedirect(reverse('fanxiangce:login'))


def photo(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)

    album = photo.album
    if not album:
        raise Http404('异常相片')
    if request.user != album.author and album.no_public:
        raise Http404('相册未公开')

    photo_index = [p.id for p in album.photos.all().order_by('order')].index(photo.id) + 1

    if request.user.is_authenticated and request.user.username != 'admin':
        likes = request.user.photo_likes.all().order_by('-id')
    else:
        likes = None

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                body = form.cleaned_data['body']
                comment = Comment(body=body, author=request.user.id, photo=photo_id)
                comment.save()
                messages.success(request, '你的评论已经发表')
                return HttpResponseRedirect(reverse('fanxiangce:photo', args=(photo_id,)))
            else:
                messages.error(request, '请先登陆')
    else:
        form = CommentForm()

    page = request.GET.get('page', 1)

    paginator = Paginator(photo.comments.all().order_by('id'), settings.FANXIANGCE_COMMENTS_PER_PAGE)
    comments = paginator.get_page(page)
    amount = len(comments)

    return render(request, 'fanxiangce/photos.html', {
        'form': form,
        'album': album,
        'amount': amount,
        'photo': photo,
        'comments': comments,
        'photo_index': photo_index,
        'photo_sum': paginator.count
    })


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']):
                messages.error(request, '用户已存在')
            else:
                if form.cleaned_data['password'] != form.cleaned_data['password2']:
                    messages.error(request, '两次密码输入不一致')
                else:
                    user = User.objects.create(
                        username=form.cleaned_data['username'],
                        password=make_password(form.cleaned_data['password']),
                        email=form.cleaned_data['email']
                    )
                    user.save()
                    user.profile.name = form.cleaned_data['name']
                    token = user.profile.generate_confirmation_token()

                    # text_content = '账户邮件确认.'
                    text_content = ''
                    confirm_url = request.build_absolute_uri(reverse('fanxiangce:confirm', args=[token]))
                    html_content = loader.render_to_string('fanxiangce/confirm.html', {'user': user, 'token': token, 'confirm_url': confirm_url})
                    msg = EmailMultiAlternatives('账户邮件确认', text_content, settings.DEFAULT_FROM_EMAIL, [user.email])
                    msg.attach_alternative(html_content, "text/html")
                    msg.send()
                    messages.info(request, '确认邮件已发送到你的邮箱，请查收')
                    return HttpResponseRedirect(reverse('fanxiangce:login'))

    return render(request, 'fanxiangce/register.html', {'form': form})

fanxiangce/templates/fanxiangce/album.html
{% extends "fanxiangce/base.html" %}
{% load static %}

{% block title %}{{ user.username }} - 翻相册{% endblock %}

{% block head %}
    {#<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>#}
    {#<link href="{% static 'fanxiangce/css/lightbox' %}" rel="stylesheet">#}
{% endblock %}

{% block body %}
    <ol class="breadcrumb" id="navigation">
        <li><a href="{% url 'fanxiangce:index' %}">首页</a></li>
{#        <li><a href="{{ url_for('.albums', username=album.author.username) }}">{% if current_user == album.author %}#}
{#            我{% else#}
{#            %}{{ album.author.name }}{% endif %}的相册</a></li>#}
{#        <li><a href="{{ url_for('.album', id=album.id) }}">《{{ album.title }}》</a></li>#}
{#        <li class="active">第{{ photo_index }}张</li>#}
{#        <li class="pull-right"><a href="{{ url_for('.album', id=album.id) }}">返回</a></li>#}
{#        <li class="pull-right"><a href="{{ url_for('main.likes', username=album.author.username) }}">#}
{#            {% if current_user ==#}
{#                album.author %}我{% else %}{{ album.author.name }}{% endif %}的喜欢</a></li>#}
    </ol>
{% endblock %}

fanxiangce/templates/fanxiangce/albums.html
{% extends "fanxiangce/base.html" %}
{% load static %}

{% block title %}{{ user.username }} - 翻相册{% endblock %}

{% block head %}
    {#<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>#}
    {#<link href="{% static 'fanxiangce/css/lightbox' %}" rel="stylesheet">#}
{% endblock %}

{% block body %}
    <ol class="breadcrumb" id="navigation">
        <li><a href="{% url 'fanxiangce:index' %}">首页</a></li>
{#        <li><a href="{{ url_for('.albums', username=album.author.username) }}">{% if current_user == album.author %}#}
{#            我{% else#}
{#            %}{{ album.author.name }}{% endif %}的相册</a></li>#}
{#        <li><a href="{{ url_for('.album', id=album.id) }}">《{{ album.title }}》</a></li>#}
{#        <li class="active">第{{ photo_index }}张</li>#}
{#        <li class="pull-right"><a href="{{ url_for('.album', id=album.id) }}">返回</a></li>#}
{#        <li class="pull-right"><a href="{{ url_for('main.likes', username=album.author.username) }}">#}
{#            {% if current_user ==#}
{#                album.author %}我{% else %}{{ album.author.name }}{% endif %}的喜欢</a></li>#}
    </ol>
{% endblock %}

fanxiangce/templates/fanxiangce/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fanxiangce/css/styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "fanxiangce/css/typing.css" %}">
    {% block head %}

    {% endblock %}
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <b>
                    <span class="fan">翻</span>
                    <span class="xiang">相</span>
                    <span class="ce">册</span>
                </b></a>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'fanxiangce:index' %}">首页</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'fanxiangce:albums' username=request.user.username %}">我的</a></li>
                {% endif %}
                <li><a href="{% url 'fanxiangce:explore' %}">探索</a></li>
{#                <li><a href="{{ url_for('main.about') }}">关于</a></li>#}
            </ul>
{##}
{#            <form class="navbar-form navbar-left" role="search">#}
{#              <div class="form-group">#}
{#                <input type="text" class="form-control" placeholder="搜索用户/相册">#}
{#              </div>#}
{#              <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>#}
{#            </form>#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a href="{{ url_for('main.new_album') }}">新建相册</a></li>#}
{#                <li><a href="{{ url_for('main.upload') }}">上传照片</a></li>#}
{#                {% if current_user.is_authenticated %}#}
{#                <li class="dropdown">#}
{#                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">#}
{#                        <span></span>#}
{#                        <img src="{{ current_user.gravatar(size=18) }}">#}
{#                        {{ current_user.name }} <strong class="caret"></strong>#}
{#                    </a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="{{ url_for('main.edit_profile', username=current_user.username) }}">编辑资料</a></li>#}
{#                        <li><a href="#">设置</a></li>#}
{#                        <li><a href="#">帮助</a></li>#}
{#                        <li class="divider"></li>#}
{#                        <li><a href="{{ url_for('auth.change_password') }}">更改密码</a></li>#}
{#                        <li><a href="{{ url_for('auth.change_email_request') }}">更改邮箱</a></li>#}
{#                        <li><a href='{{ url_for("auth.logout") }}'>注销</a></li>#}
{#                    </ul>#}
{##}
{##}
{#                </li>#}
{##}
{#                {% else %}#}
{#                <li><a href="{{ url_for('auth.login') }}">登录</a></li>#}
{#            </ul>#}
{##}
{#            {% endif %}#}

        </div>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
        <p class="message-p {% if message.tags %}  bg-{{ message.tags }} {% endif %}">{{ message }}</p>
    {% endfor %}
{% endif %}

{% block body %}
{% endblock %}
</body>
</html>

fanxiangce/templates/fanxiangce/confirm.html
<p>亲爱的 {{ user.username }},</p>
<p>欢迎来到 <b>翻相册</b>!</p>
<p>点击下面的链接确认你的账户： <br>
{#    <a href="{{ url_for('auth.confirm', token=token, _external=True) }}">{{ url_for('auth.confirm', token=token, _external=True) }}</a></p>#}
    <a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<p>如果你的email程序不支持链接点击，请将上面的地址拷贝至你的浏览器的地址栏进入翻相册。</p>
<p>感谢你对翻相册的支持，祝你在翻相册获得愉快的体验。</p>
<p>翻相册 http://fanxiangce.com/</p>
<p><small>(这是一封自动生成的email，请勿回复。)</small></p>

fanxiangce/templates/fanxiangce/explore.html
{% extends "fanxiangce/base.html" %}
{% load static %}

{% block title %}翻相册{% endblock %}

{% block head %}
    {#<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>#}
    {#<link href="{% static 'fanxiangce/css/lightbox' %}" rel="stylesheet">#}
{% endblock %}

{% block body %}
    <ol class="breadcrumb" id="navigation">
        <li><a href="{% url 'fanxiangce:index' %}">首页</a></li>
    </ol>
{% endblock %}

fanxiangce/templates/fanxiangce/form_template.html
{% csrf_token %}
{% for field in form %}
    <div class="form-line">
        <div class="field-label-tag">
            {{ field.label_tag }}
        </div>
        <div class="field-field">
            {{ field }}
        </div>
        <div class="field-errors">
            {{ field.errors }}
        </div>
    </div>

{% endfor %}

fanxiangce/templates/fanxiangce/index.html
{% extends "fanxiangce/base.html" %}
{% load static %}
{% block title %}
    首页
{% endblock %}

{% block body %}
    <div class="container">
        <h3>我的关注</h3>
    </div>
    <hr>
    <div class="container">
        <div class="row grid">
            {% for photo in photos %}
                {{ photo.url }}
                {% if photo.album.no_public == False %}
                    <div class="explore-image grid-item">
                        <a class="thumbnail" href="{% url 'fanxiangce:photo' photo_id=photo.id %}">
                            <img class="img-responsive" src="{{ photo.url_t }}">
                        </a>
                        <div class="info">
                            <span>上传于{{ photo.timestamp }}</span>
                            <span>作者：<a href="{% url 'fanxiangce:albums' username=photo.author.username %}">{{ photo.author.name }}</a></span><br>
                            <span>相册：<a href="{% url 'fanxiangce:album' album_id=photo.album.id %}">{{ photo.album.title }}</a></span>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            {% if not photos %}
                <h4>你还没有关注任何人，先去<a href="{% url 'fanxiangce:explore' %}">探索</a>一下吧！</h4>
            {% endif %}
        </div>
    </div>

{% endblock %}

fanxiangce/templates/fanxiangce/login.html
{% extends "fanxiangce/base.html" %}
{% load static %}

{% block title %}翻相册 - 登陆{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>登陆</h1>
    </div>
    <div>
        <form action="{% url 'fanxiangce:login' %}" method="post">
            {% include 'fanxiangce/form_template.html' %}
            <input class="btn btn-primary login-button" type="submit" value="登陆">
        </form>
        <br>
        <p class="p-register">新用户？点击<a href="{% url 'fanxiangce:register' %}">这里</a>注册。</p>
    </div>
{% endblock %}

fanxiangce/templates/fanxiangce/photos.html
{% extends "fanxiangce/base.html" %}
{% load static %}

{% block title %}{{ album.title }} - 翻相册{% endblock %}

{% block head %}
    {#<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>#}
    {#<link href="{% static 'fanxiangce/css/lightbox' %}" rel="stylesheet">#}
{% endblock %}

{% block body %}
    <ol class="breadcrumb" id="navigation">
        <li><a href="{% static 'fanxiangce:index' %}">首页</a></li>
{#        <li><a href="{{ url_for('.albums', username=album.author.username) }}">{% if current_user == album.author %}#}
{#            我{% else#}
{#            %}{{ album.author.name }}{% endif %}的相册</a></li>#}
{#        <li><a href="{{ url_for('.album', id=album.id) }}">《{{ album.title }}》</a></li>#}
{#        <li class="active">第{{ photo_index }}张</li>#}
{#        <li class="pull-right"><a href="{{ url_for('.album', id=album.id) }}">返回</a></li>#}
{#        <li class="pull-right"><a href="{{ url_for('main.likes', username=album.author.username) }}">#}
{#            {% if current_user ==#}
{#                album.author %}我{% else %}{{ album.author.name }}{% endif %}的喜欢</a></li>#}
    </ol>
{% endblock %}

fanxiangce/templates/fanxiangce/register.html
{% extends "fanxiangce/base.html" %}
{% load static %}

{% block title %}翻相册 - 注册{% endblock %}

{% block body %}
    <div class="page-header">
        <h1>注册</h1>
    </div>
    <form action="{% url 'fanxiangce:register' %}" method="post">
        {% include 'fanxiangce/form_template.html' %}
        <input class="btn btn-primary login-button" type="submit" value="注册">
    </form>
    <br>
{% endblock %}

fanxiangce/templates/fanxiangce/unconfirmed.html
{% extends "fanxiangce/base.html" %}

{% block title %}翻相册 - 确认账户{% endblock %}

{% block body %}
<div class="page-header">
    <h1>你好，{{ request.user.username }}！</h1>
    <h3>你还没有确认你的账户，请前往你的邮箱查收确认邮件。</h3>
    <p>
        在开始你的翻相册之旅前，你需要确认你的账户。检查你的收件箱，点击翻相册的确认邮件里的链接。
        <br><br>
        没有收到？点击<a href="{% url 'fanxiangce:resend_confirmation' %}">这里</a>重新发送。
    </p>
</div>
{% endblock %}